### ISSUE TITLE
A question about the setting in vocab.json

### ISSUE THREAD

**Issue by elevenofji** [ucfnlp/joint-parse-n-summarize#1]
Hi! I have a question about the code in ./vocabulary/vocabulary.py

In the `setup`  function, you create a `typeFreq_Full` dict, but why:

 `if (key not in typeFreq_output) and (typeFreq_input[key] >= self.minFreq * 5):`

Why is `self.minFreq * 5`, not `self.minFreq` ?

**Comment by KaiQiangSong** [comment]
> Hi! I have a question about the code in ./vocabulary/vocabulary.py
> 
> In the `setup` function, you create a `typeFreq_Full` dict, but why:
> 
> `if (key not in typeFreq_output) and (typeFreq_input[key] >= self.minFreq * 5):`
> 
> Why is `self.minFreq * 5`, not `self.minFreq` ?

Input usually has more words there. So when setting up a threshold, it should be larger.

**Comment by elevenofji** [comment]
ok..Thx for ur replying
